{
 "title": "INTEGRASI SISTEM MONITORING UPTIME KUMA X ROUTER MIKROTIK",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in [Uptime Kuma](https://github.com/louislam/uptime-kuma)\r\n\r\nImproved by https://github.com/EliottGoye",
 "tags": [ "uptime-kuma" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$type\"}, monitor_name)"
    }
   },
   {
    "name": "Index",
    "query": {
     "query": "label_values(ifHighSpeed{instance=\"$Instance\"},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,instance)"
    }
   },
   { "name": "Offline_monitor", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  { "title": "Device info & Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "description": "Panel Router model menunjukan Tipe router yang \ndigunakan",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  { "title": "System Uptime", "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 } },
  {
   "title": "Total SNMP time (walk and processing)",
   "type": "stat",
   "description": " total waktu yang dibutuhkan \nuntuk proses SNMP walk dan processing data dari \nperangkat router Mikrotik sampai datanya siap dikirim \nke Prometheus",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Time SNMP walk/bulkwalk took",
   "type": "stat",
   "description": "Waktu yang dibutuhkan untuk menjalankan proses SNMP \nwalk atau bulkwalk dalam pengambilan data dari perangkat. \nIni hanya bagian dari total waktu scraping SNMP",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "scrape pdus returned",
   "type": "stat",
   "description": " Menunjukkan jumlah PDU (Protocol Data Units) \nyang dikembalikan selama proses SNMP scraping dari \nperangkat. Jika nilai terlalu tinggi, \nbisa jadi karena terlalu banyak OID yang ditarik, dan itu bisa \nmenyebabkan scraping lambat. ",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  { "title": "CPU LOAD", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 } },
  { "title": "CPU Temp", "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 } },
  { "title": "system disk load", "gridPos": { "h": 5, "w": 3, "x": 8, "y": 4 } },
  {
   "title": "Simple Queue (In/Out/Dropped/PCQ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "Panel Title", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 } },
    { "title": "Queue $queuesimple_name", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 } }
   ]
  },
  { "title": "Interface Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "Interface Traffic", "gridPos": { "h": 7, "w": 12, "x": 1, "y": 11 } },
  { "title": "CCTV -UP TIME KUMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "TOTAL SEMUA MONITOR", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 } },
  {
   "title": "Total Online Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Offline Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(monitor_status == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time (15m)",
   "type": "stat",
   "description": "Panel ini menunjukkan waktu rata-rata respon \n(response time) dari semua monitor selama rentang \nwaktu tertentu",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (2h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TOP 5 CCTV PALING SERING MATI", "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 } },
  {
   "title": "SLA",
   "type": "timeseries",
   "description": " menunjukkan persentase tingkat ketersediaan \nlayanan/monitor selama periode waktu tertentu",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(0*(monitor_status{monitor_name=~\"$monitor\"}!=1)) or (monitor_status{monitor_name=~\"$monitor\"}*100)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  { "title": "$monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "monitor" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(0*(monitor_status{monitor_name=~\"$monitor\"}!=1)) or (monitor_status{monitor_name=~\"$monitor\"}*100)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "description": "waktu yang dibutuhkan untuk merespons permintaan",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(monitor_response_time{monitor_name=~\"$monitor\"}[24h])",
     "legendFormat": "AVG 24H"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}